import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Head, router, useForm } from '@inertiajs/react';
import { Download, Eye, FileText, Image as ImageIcon, Plus, Trash2, UploadCloud, X } from 'lucide-react';
import { AppLayout } from '@/Components/layout/AppLayout';
import { PageHeader } from '@/Components/shared/PageHeader';
import { StatusBadge } from '@/Components/shared/StatusBadge';
import { MoneyDisplay } from '@/Components/shared/MoneyDisplay';
import { Button } from '@/Components/ui/button';
import { Input } from '@/Components/ui/input';
import { Textarea } from '@/Components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/Components/ui/select';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/Components/ui/dialog';
import { PageProps } from '@/types';
import { formatNumericInput, parseNumericInput } from '@/lib/format';

type Item = { item: string; quantity: number | string; unit_price: number | string; supplier: string };
type Projection = { id: number; title: string; department?: { name: string }; expected_at?: string; priority: string; status: string; total_amount: string; justification?: string; notes?: string; items: Item[]; attachments: { id: number; file_name: string; url: string; mime_type?: string }[] };
type Props = PageProps<{ projections: Projection[]; departments: { id: number; name: string }[] }>;
type PreviewFile = { name: string; url: string; mimeType: string; temporary?: boolean };

const blankItem = (): Item => ({ item: '', quantity: 1, unit_price: 0, supplier: '' });
const statuses = ['Borrador', 'En revisión', 'Aprobada', 'Rechazada', 'Ejecutada'];

export default function FinancialProjections({ auth, projections, departments }: Props) {
    const [open, setOpen] = useState(false);
    const [editing, setEditing] = useState<Projection | null>(null);
    const [items, setItems] = useState<Item[]>([blankItem()]);
    const [selectedFiles, setSelectedFiles] = useState<File[]>([]);
    const [preview, setPreview] = useState<PreviewFile | null>(null);
    const { data, setData, post, processing, errors, reset, transform } = useForm<any>({ title: '', department_id: '', justification: '', expected_at: '', priority: 'Media', status: 'Borrador', notes: '', items: [blankItem()], attachments: [] });

    const total = useMemo(() => items.reduce((sum, item) => sum + Number(item.quantity || 0) * Number(item.unit_price || 0), 0), [items]);
    const selectedFilePreviews = useMemo(() => selectedFiles.map((file) => ({ file, url: URL.createObjectURL(file) })), [selectedFiles]);
    useEffect(() => () => selectedFilePreviews.forEach(({ url }) => URL.revokeObjectURL(url)), [selectedFilePreviews]);
    useEffect(() => { setData('items', items); }, [items]);

    function startCreate() { setEditing(null); setItems([blankItem()]); setSelectedFiles([]); reset(); setData('priority', 'Media'); setData('status', 'Borrador'); setOpen(true); }
    function startEdit(row: Projection) { setEditing(row); setItems(row.items.length ? row.items : [blankItem()]); setSelectedFiles([]); Object.entries(row).forEach(([key, value]) => { if (['items', 'attachments', 'department'].includes(key)) return; setData(key, value ?? ''); }); setData('attachments', []); setOpen(true); }
    function updateItem(index: number, key: keyof Item, value: string) { setItems((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: key === 'quantity' || key === 'unit_price' ? value : value } : item)); }
    function submit(event: FormEvent) { event.preventDefault(); transform((current: Record<string, any>) => ({ ...current, items, _method: editing ? 'put' : undefined })); const options = { forceFormData: true, preserveScroll: true, onSuccess: () => setOpen(false) }; editing ? post(`/financial-projections/${editing.id}`, options) : post('/financial-projections', options); }
    function remove(id: number) { if (window.confirm('¿Eliminar esta proyección?')) router.delete(`/financial-projections/${id}`, { preserveScroll: true }); }
    function convert(id: number) { if (window.confirm('¿Crear solicitudes de compra a partir de esta proyección?')) router.post(`/financial-projections/${id}/convert-to-purchase`, {}, { preserveScroll: true }); }
    function selectFiles(files: FileList | null) { const nextFiles = Array.from(files ?? []); setSelectedFiles(nextFiles); setData('attachments', nextFiles); }
    function openExistingFile(file: Projection['attachments'][number]) { setPreview({ name: file.file_name, url: file.url, mimeType: file.mime_type ?? '' }); }
    function openSelectedFile(file: File) { setPreview({ name: file.name, url: URL.createObjectURL(file), mimeType: file.type, temporary: true }); }
    function closePreview() { if (preview?.temporary) URL.revokeObjectURL(preview.url); setPreview(null); }
    function formatBytes(bytes: number) { return bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / 1024 / 1024).toFixed(2)} MB`; }

    return <AppLayout user={auth.user}>
        <Head title="Proyecciones financieras" />
        <div className="mx-auto flex max-w-7xl flex-col gap-6">
            <PageHeader title="Proyecciones financieras" description="Planifica adquisiciones futuras con presupuesto, cotizaciones y evidencia visual." actions={<Button onClick={startCreate}><Plus className="h-4 w-4" />Nueva proyección</Button>} />
            <div className="grid gap-4 md:grid-cols-3"><div className="rounded-lg border border-white/10 bg-white/5 p-4"><p className="text-sm text-muted-foreground">Total proyectado</p><p className="mt-2 text-2xl font-semibold"><MoneyDisplay value={projections.reduce((sum, p) => sum + Number(p.total_amount), 0)} /></p></div><div className="rounded-lg border border-white/10 bg-white/5 p-4"><p className="text-sm text-muted-foreground">En revisión</p><p className="mt-2 text-2xl font-semibold">{projections.filter((p) => p.status === 'En revisión').length}</p></div><div className="rounded-lg border border-white/10 bg-white/5 p-4"><p className="text-sm text-muted-foreground">Aprobadas</p><p className="mt-2 text-2xl font-semibold">{projections.filter((p) => p.status === 'Aprobada').length}</p></div></div>
            <div className="overflow-x-auto rounded-lg border border-white/10"><table className="w-full text-left text-sm"><thead className="bg-white/5 text-muted-foreground"><tr>{['Proyección', 'Departamento', 'Fecha estimada', 'Prioridad', 'Total', 'Estado', 'Archivos', ''].map((heading) => <th key={heading} className="px-4 py-3">{heading}</th>)}</tr></thead><tbody>{projections.map((row) => <tr key={row.id} className="border-t border-white/10"><td className="px-4 py-3 font-medium">{row.title}</td><td className="px-4 py-3">{row.department?.name ?? '-'}</td><td className="px-4 py-3">{row.expected_at ?? '-'}</td><td className="px-4 py-3">{row.priority}</td><td className="px-4 py-3"><MoneyDisplay value={Number(row.total_amount)} /></td><td className="px-4 py-3"><StatusBadge status={row.status} /></td><td className="px-4 py-3">{row.attachments.length > 0 ? <div className="flex gap-1">{row.attachments.map((file) => <button key={file.id} type="button" title={file.file_name} onClick={() => openExistingFile(file)} className="rounded-md p-1 text-[#D4AF37] hover:bg-[#D4AF37]/10"><FileText className="h-4 w-4" /></button>)}</div> : <span className="text-white/40">-</span>}</td><td className="space-x-1 px-4 py-3 text-right">{row.status === 'Aprobada' && <Button variant="outline" size="sm" onClick={() => convert(row.id)}>Pasar a compras</Button>}<Button variant="outline" size="sm" onClick={() => startEdit(row)}>Editar</Button> <Button variant="destructive" size="sm" onClick={() => remove(row.id)}><Trash2 className="h-4 w-4" /></Button></td></tr>)}</tbody></table></div>
        </div>
        {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><form onSubmit={submit} className="max-h-[90vh] w-full max-w-3xl space-y-5 overflow-y-auto rounded-xl border border-white/10 bg-[#0D0A0A] p-6"><h2 className="text-xl font-semibold">{editing ? 'Editar proyección' : 'Nueva proyección'}</h2><div className="grid gap-4 sm:grid-cols-2"><label className="space-y-2 sm:col-span-2"><span>Título *</span><Input value={data.title} onChange={(e) => setData('title', e.target.value)} /></label><label className="space-y-2"><span>Departamento</span><Select value={String(data.department_id || 'none')} onValueChange={(v) => setData('department_id', v === 'none' ? '' : v)}><SelectTrigger><SelectValue placeholder="Seleccionar" /></SelectTrigger><SelectContent><SelectItem value="none">Sin seleccionar</SelectItem>{departments.map((d) => <SelectItem key={d.id} value={String(d.id)}>{d.name}</SelectItem>)}</SelectContent></Select></label><label className="space-y-2"><span>Fecha estimada</span><Input type="date" value={data.expected_at ?? ''} onChange={(e) => setData('expected_at', e.target.value)} /></label><label className="space-y-2"><span>Prioridad</span><Select value={data.priority} onValueChange={(v) => setData('priority', v)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{['Baja', 'Media', 'Alta'].map((v) => <SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></label><label className="space-y-2"><span>Estado</span><Select value={data.status} onValueChange={(v) => setData('status', v)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{statuses.map((v) => <SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></label><label className="space-y-2 sm:col-span-2"><span>Justificación</span><Textarea value={data.justification ?? ''} onChange={(e) => setData('justification', e.target.value)} /></label></div>
            <div className="space-y-3"><div className="flex items-center justify-between"><h3 className="font-medium">Adquisiciones</h3><Button type="button" variant="outline" size="sm" onClick={() => setItems([...items, blankItem()])}><Plus className="h-4 w-4" />Agregar artículo</Button></div>{items.map((item, index) => <div key={index} className="grid gap-2 rounded-lg border border-white/10 p-3 sm:grid-cols-4"><Input placeholder="Artículo o servicio" value={item.item} onChange={(e) => updateItem(index, 'item', e.target.value)} /><Input placeholder="Cantidad" type="text" inputMode="numeric" value={formatNumericInput(item.quantity)} onChange={(e) => updateItem(index, 'quantity', parseNumericInput(e.target.value))} /><Input placeholder="Precio estimado" type="text" inputMode="decimal" value={formatNumericInput(item.unit_price)} onChange={(e) => updateItem(index, 'unit_price', parseNumericInput(e.target.value))} /><div className="flex gap-2"><Input placeholder="Proveedor" value={item.supplier} onChange={(e) => updateItem(index, 'supplier', e.target.value)} />{items.length > 1 && <Button type="button" variant="destructive" size="icon" onClick={() => setItems(items.filter((_, i) => i !== index))}><Trash2 className="h-4 w-4" /></Button>}</div></div>)}<p className="text-right text-lg font-semibold">Total: <MoneyDisplay value={total} /></p></div>
            <div className="space-y-2"><span>Cotizaciones y fotos</span><label className="group flex cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-white/20 bg-white/[0.03] px-4 py-6 text-center transition hover:border-[#D4AF37]/70 hover:bg-[#D4AF37]/[0.06]"><UploadCloud className="mb-2 h-8 w-8 text-[#D4AF37]" /><span className="text-sm font-medium text-white">Arrastra archivos aquí o haz clic para seleccionarlos</span><span className="mt-1 text-xs text-muted-foreground">PDF, Excel, Word o imágenes · máximo 10 archivos de 10 MB</span><Input className="sr-only" type="file" multiple accept=".pdf,.xlsx,.xls,.doc,.docx,image/*" onChange={(e) => selectFiles(e.target.files)} /></label>{selectedFiles.length > 0 && <div className="grid gap-2 sm:grid-cols-2">{selectedFilePreviews.map(({ file, url }) => <button key={`${file.name}-${file.lastModified}`} type="button" onClick={() => openSelectedFile(file)} className="flex items-center gap-3 rounded-lg border border-white/10 bg-white/[0.04] p-3 text-left transition hover:border-[#D4AF37]/60"><span className="flex h-10 w-10 shrink-0 items-center justify-center overflow-hidden rounded-md bg-[#D4AF37]/10 text-[#D4AF37]">{file.type.startsWith('image/') ? <img src={url} alt="" className="h-full w-full object-cover" /> : <FileText className="h-5 w-5" />}</span><span className="min-w-0"><span className="block truncate text-sm text-white">{file.name}</span><span className="text-xs text-muted-foreground">{file.type || 'Archivo'} · {formatBytes(file.size)}</span></span><Eye className="ml-auto h-4 w-4 shrink-0 text-white/50" /></button>)}</div>}{editing?.attachments.length ? <div className="space-y-2"><p className="text-xs text-muted-foreground">Archivos guardados</p><div className="grid gap-2 sm:grid-cols-2">{editing.attachments.map((file) => <button key={file.id} type="button" onClick={() => openExistingFile(file)} className="flex items-center gap-3 rounded-lg border border-white/10 bg-white/[0.04] p-3 text-left transition hover:border-[#D4AF37]/60"><span className="flex h-10 w-10 items-center justify-center rounded-md bg-[#D4AF37]/10 text-[#D4AF37]"><FileText className="h-5 w-5" /></span><span className="min-w-0 truncate text-sm text-white">{file.file_name}</span><Eye className="ml-auto h-4 w-4 shrink-0 text-white/50" /></button>)}</div></div> : null}</div><label className="block space-y-2"><span>Notas</span><Textarea value={data.notes ?? ''} onChange={(e) => setData('notes', e.target.value)} /></label>{Object.keys(errors).length > 0 && <p className="text-sm text-red-300">Revisa los campos marcados antes de guardar.</p>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancelar</Button><Button type="submit" disabled={processing}>{processing ? 'Guardando...' : 'Guardar proyección'}</Button></div></form></div>}
        <Dialog open={Boolean(preview)} onOpenChange={(value) => !value && closePreview()}><DialogContent className="max-h-[90vh] max-w-4xl border-white/10 bg-[#0D0A0A]"><DialogHeader><DialogTitle className="truncate pr-8">{preview?.name}</DialogTitle><DialogDescription>Vista previa del archivo seleccionado.</DialogDescription></DialogHeader>{preview && (preview.mimeType.startsWith('image/') ? <img src={preview.url} alt={preview.name} className="max-h-[65vh] w-full rounded-lg object-contain" /> : preview.mimeType === 'application/pdf' || preview.url.toLowerCase().includes('.pdf') ? <iframe src={preview.url} title={preview.name} className="h-[65vh] w-full rounded-lg border border-white/10" /> : <div className="flex flex-col items-center gap-4 rounded-lg border border-white/10 bg-white/[0.03] p-10 text-center"><FileText className="h-16 w-16 text-[#D4AF37]" /><p className="text-sm text-white/80">Este formato no se puede visualizar directamente en el navegador.</p><a href={preview.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-md bg-[#C1002B] px-4 py-2 text-sm font-medium text-white hover:bg-[#A80025]"><Download className="h-4 w-4" />Abrir o descargar</a></div>)}<button type="button" onClick={closePreview} className="absolute right-4 top-4 rounded-md p-1 text-white/60 hover:bg-white/10 hover:text-white"><X className="h-5 w-5" /></button></DialogContent></Dialog>
        {open && <button type="button" onClick={() => setOpen(false)} aria-label="Cerrar modal" style={{ position: 'fixed', top: 'calc(5vh + 12px)', right: 'calc(50% - 22rem)', zIndex: 9999 }} className="rounded-sm p-1 text-white/70 hover:bg-white/10 hover:text-white"><X className="h-4 w-4" /></button>}
    </AppLayout>;
}
